Locale: en

AssaultEnable: false # system to damage a region, incurring money damages. If enough damage is inflicted, ownership is lost. Ownership can be restored, and the region repaired, by paying damages
AssaultDamagesCapPercent: 1.0 # percentage of the total wealth of all members of the region which is the maximum damages that can be inflicted
AssaultCooldownHours: 24 # time before a region owner can have one of their regions assaulted again
AssaultDelay: 1800 # time (in seconds) between when an assault is announced, and when it happens
AssaultDuration: 1800 # time (in seconds) for the assault
AssaultCostPercent: 0.25 # percentage of the total wealth of all members of the region which is the cost to assault it
AssaultDamagesPerBlock: 15 # the damages incurred for every block that would have been destroyed in an assault
AssaultMaxBalance: 5000000 # Maximum balance of each player that will be contributed to the cost & damages (previously hard coded at 5 million)
AssaultRequiredDefendersOnline: 2 # At least this many members or owners must be online for the region to be assaulted
AssaultRequiredOwnersOnline: 1 # At least this many owners must be online for the region to be assaulted, set to 0 to ignore
AssaultOwnerWeightPercent: 1.0 # Percentage of each Owner's balance (under the maximum) to include in the total cost & damages (Can be greater than 100)
AssaultMemberWeightPercent: 1.0 # Percentage of each Member's balance (under the maximum) to include in the total cost & damages (Can be greater than 100)
AssaultChunkSaveTime: 5 # Max time (in milliseconds) per tick spent saving chunks (per assault).  Reduce this if the server lags when an assault is started.
AssaultChunkRepairTime: 5 # Max time (in milliseconds) per tick spent repairing chunks (per assault).  Reduce this if the server lags when an assaulted region is repaired.
AssaultDestroyableBlocks: # these blocks will be removed if destroyed in assault. Other blocks will not be removed, but still count for damages. Don't include craft flyblocks, or blocks with metadata, or you can have issues.
  - STONE
  - GRASS_BLOCK
  - DIRT
  - COBBLESTONE
  - SAND
  - GRAVEL
  - IRON_ORE
  - COAL_ORE
  - OAK_LEAVES
  - SPONGE
  - SANDSTONE
  - DEAD_BUSH
  - DANDELION
  - POPPY
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - TNT
  - MOSSY_COBBLESTONE
  - FARMLAND
  - COBBLESTONE_STAIRS
  - REDSTONE_ORE
  - SNOW
  - ICE
  - SNOW_BLOCK
  - CACTUS
  - STONE_BRICKS
  - BRICK_STAIRS
  - SANDSTONE_STAIRS
  - EMERALD_ORE
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_STAIRS
  - PRISMARINE
  - SEA_LANTERN
  - PACKED_ICE
  - SUNFLOWER
  - RED_SANDSTONE
  - RED_SANDSTONE_STAIRS
  - RED_SANDSTONE_SLAB
  - FROSTED_ICE

SiegeEnable: true
SiegeTaskSeconds: 600 # Seconds per siege message, defaults to 600 (10 minutes)
