name: Movecraft-Warfare
depend: [Movecraft, Movecraft-Repair, WorldGuard, WorldEdit]
version: ${project.version}
api-version: 1.10
description: Movecraft Warfare Addon
authors: [TylerS1066, cccm5, eirik1996, BaccaYarro]
website: https://github.com/APDevTeam/Movecraft-Warfare
main: net.countercraft.movecraft.warfare.MovecraftWarfare
commands:
  siege:
    description: If the region you are standing in is configured for Siege, lays siege to it
    usage: /siege
  assaultinfo:
    description: Gives you information about the region(s) you are in, and if they are available for Assault
    usage: /assaultinfo
  assault:
    description: Begins an Assault on the specified region
    usage: /assault <regionname>
  assaultrepair:
    description: Repairs a region using admin magic
    usage: /assaultrepair