name: Movecraft-Warfare
depend: [Movecraft, Movecraft-Repair, Movecraft-WorldGuard]
version: ${project.version}
api-version: 1.14
description: Movecraft Warfare Addon
authors: [TylerS1066, cccm5, eirik1996, BaccaYarro]
website: https://github.com/APDevTeam/Movecraft-Warfare
main: net.countercraft.movecraft.warfare.MovecraftWarfare
commands:
  siege:
    description: If the region you are standing in is configured for Siege, lays siege to it
    usage: /siege
  assaultinfo:
    description: Gives you information about the region(s) you are in, and if they are available for Assault
    usage: /assaultinfo
    permission: movecraft.assaultinfo
  assault:
    description: Begins an Assault on the specified region
    usage: /assault <regionname>
    permission: movecraft.assault
  assaultbar:
    description: Toggle the assault bar feature
    permission: movecraft.warfare.assaultbar
  assaultrepair:
    description: Repairs a region using admin magic
    usage: /assaultrepair
    permission: movecraft.assault.adminrepair
